apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  type: {{ .Values.castService.service.type }}
  ports:
    - port: {{ .Values.castService.service.port }}
      targetPort: {{ .Values.castService.service.port }}
  selector:
    app: cast-service
