apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: {{ .Values.postgres.usernameb64 }}
  postgres-password: {{ .Values.postgres.passwordb64 }}
  postgres-db: {{ .Values.postgres.databaseb64 }}

