apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  type: {{ .Values.movieService.service.type }}
  ports:
    - port: {{ .Values.movieService.service.port }}
      targetPort: {{ .Values.movieService.service.port }}
  selector:
    app: movie-service
