apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{ .Values.postgres.nodePort }}
  selector:
    app: postgresql