apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  storageClassName: local-path      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  storageClassName: local-path

